[package]
name = "rakefile"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = { version = "1.10.5", default-features = false }
robuild = "0.0.20"

[[bin]]
path = "src/rake.rs"
name = "rakefile"
