all: hello build build/foo build/bar

hello1: hello build/foo

hello:
	echo hello from Rakefile!

build:
	mkdir -p build

build/foo: src/foo.c
	cc -o $t $d

build/bar: src/bar.c src/bar.h
	cc -o $t $d[0]

.ALWAYS: hello build/foo
