all: hello build/foo build/bar

hello:
    echo hello from Rakefile!

build/foo: src/foo.c
    mkdir -p build
    cc -o $t $d

build/bar: src/bar.c src/bar.h
    mkdir -p build
    cc -o $t $d

.ALWAYS: hello
